// Script pour géocoder tous les sites depuis la liste fournie
// Utilisation: Copiez ce script dans la console du navigateur sur interne.html

const sitesList = [
    "Carrefour Market - La Brillanne",
    "Intermarché - Saint-Nazaire",
    "Garage Pyrame - Aix-en-Provence",
    "Supermarché Match - Villeneuve-d'Ascq Haute Borne",
    "Intermarché - Bailleul",
    "Intermarché - Ramonville-Saint-Agne",
    "Le Village des Talents Créatifs - Puget-sur-Argens",
    "Carrefour - Strasbourg Mundo'",
    "Carrefour - Rennes-Pacé",
    "Carrefour - Val d'Yerres",
    "Carrefour - Amphion",
    "Super U - Vierzon",
    "E.Leclerc - Ranger Nancyleuve",
    "La Boucherie - Epinal",
    "Le Dépôt - Ussac",
    "Spar - Saze",
    "Super U - Rosporden",
    "KFC - Montélimar",
    "KFC - Valence",
    "KFC - Bourgoin-Jallieu",
    "La Boutique du Menuisier - Montélimar",
    "Super U - Tavaux",
    "Carrefour - Massy",
    "Système U - Le Faou",
    "Carrefour - Wittenheim",
    "Bio Attitudes - Saint-Flour",
    "Super U - Arbois",
    "Station Karcher Plan de Campagne - Les Pennes-Mirabeau",
    "Intermarché Super - Labarthe-sur-Lèze",
    "Electroad - Haute-Goulaine",
    "Station de Lavage WAP - Bias",
    "Intermarché - Jarville-la-Malgrange",
    "E.Leclerc - Brissac Quince",
    "Intermarché Super - Montivilliers",
    "Mr. Bricolage - Chalonnes-sur-Loire",
    "Soccer - Rennes",
    "Mr. Bricolage - Les Touches",
    "Super U - Trèbes",
    "Intermarché - Ploeren",
    "Centre Commercial Les Eleis - Cherbourg-en-Cotentin (Dernier étage du parking)",
    "Intermarché Super - Lentigny",
    "Weldom - Saujon",
    "But - Fourmies",
    "Intermarché Super - Chaveignes",
    "Mr. Bricolage - Belz",
    "Carrefour Market - Nonancourt",
    "Skill Telecom - Lannion",
    "Intermarché - Terrasson-Lavilledieu",
    "Intermarché - Callac",
    "Intermarché - Elven",
    "Intermarché - Poilly-lez-Gien",
    "Intermarché - Landévant",
    "Auchan - Haguenau",
    "Mairie De Montbronn - Montbronn",
    "Indigo Haussmann Galeries Lafayette",
    "Carrefour - Ermont",
    "Bricomarché - Chauny",
    "Système U - Gevrey Chambertin",
    "Tonton Michel - Villeneuve-lès-Bouloc",
    "Intermarché - Faremoutiers",
    "Intermarché - Rupt-sur-Moselle",
    "Système U - Saint-Denis-de-l'Hôtel",
    "Weldom - Hésingue",
    "Super U - Pouxeux",
    "Intermarché - Montchanin",
    "Intermarché - Yvrac",
    "Intermarché - Gasny",
    "Intermarché - Lorient",
    "Flash Lavage - Tarbes",
    "Sogemat Energie - Station Cournon-d'Auvergne",
    "Intermarché - Longwy",
    "Centre commercial Okabé",
    "O'Pizzicato - Entzheim",
    "O'Pizzicato - Wiwersheim",
    "Intermarché - Carmaux",
    "Intermarché - Langres",
    "Super U - Pouilly-en-Auxois",
    "Intermarché Super - Broons",
    "Super U - Le Havre",
    "Weldom - Sierentz",
    "Mr. Bricolage - Céret",
    "Super U - Vernou-sur-Brenne",
    "Intermarché - Bonnat",
    "Intermarché - Dun-le-Palestel",
    "Netto - Guéret",
    "Système U - Saumur",
    "Intermarché - Anneyron",
    "Balladins - Dijon",
    "Comfort Hotel Longvic",
    "Intermarché - Veneux les Sablons",
    "Intermarché - Bolbec",
    "Le Pavé des Minimes - Toulouse",
    "Carrefour - Dunkerque",
    "Carrefour - Vichy",
    "Carrefour - Forbach",
    "Carrefour - Sarreguemines",
    "Super U - Marmande",
    "Carrefour Contact - Tournay",
    "Netto - Marseille",
    "Mr. Bricolage - Pont-l'Évêque",
    "Mr. Bricolage - Touques",
    "Carrefour Market Pont-Audemer (27)",
    "Mr. Bricolage - Avranches",
    "Intermarché - Nousty",
    "King Jouet - Brétigny-sur-Orge",
    "Tissus des Ursules - Maurepas",
    "B&M - Vernouillet",
    "Darty - Avignon",
    "Intermarché - Cornebarrieu",
    "Team Square - Hénin-Beaumont",
    "Karcher - Aire-sur-la-Lys",
    "Intermarché - Retournac",
    "Super U - Amiens",
    "Intermarché Super - Capvern",
    "Carrefour Contact - Salies-du-Salat",
    "Super U - Neuilly-sur-Marne",
    "Intermarché Super - Illiers-Combray",
    "SCI - Edizaynn",
    "Mercure - Porte de Vanves",
    "Carrefour - Clermont Ferrand",
    "Basic Fit - Beauvais",
    "KFC - Ennetières-en-Weppes",
    "Five Guys - Franconville",
    "Mobalpa - Herblay (Langevin)",
    "Basic Fit - La Valette-du-Var",
    "Darty - La Valette",
    "Basic Fit - Orange",
    "La Maison Convertible - Les Pennes-Mirabeau",
    "Biocoop - Saint-Thibault",
    "Besson Chaussures - Sorgues",
    "Centre Commercial So Green - Seclin",
    "Bureau Vallée - L'Union",
    "Intermarché - Commercy",
    "Intermarché - Soumoulou",
    "Les comptoirs de la Bio Saran (45)",
    "Intermarché - Agen",
    "Super U - Rohrbach-lès-Bitche",
    "Bricomarché - Rouxmesnil-Bouteilles",
    "Intermarché - Merlevenez",
    "Intermarché - Lillebonne",
    "Intermarché Super - Balma",
    "Intermarché Super - Bartenheim",
    "Novotel - Bagnolet",
    "SCI - Chabal",
    "Intermarché - Condom",
    "Super U - Laguenne",
    "Basic Fit - Sartrouville",
    "Intermarché - Vitry-le-François",
    "Intermarché - Verquin",
    "Intermarché Super - Hersin-Coupigny",
    "Hyper U - Reims",
    "Intermarché Super - Toucy",
    "Intermarché - Rang-du-Fliers",
    "Intermarché - Isneauville",
    "Brico Cash - Champagne-sur-Oise",
    "Centre Commercial De L'Arche - La Fouillouse",
    "Intermarché - Montauban",
    "Intermarché Super - Gratentour",
    "La Panetières",
    "Optical Center - Brive-la-Gaillarde",
    "Retail Park - Brive-la-Gaillarde",
    "Darty - Étampes",
    "Electro Depôt - Marseille",
    "Ibis Styles - Douai Gare Gayant Expo",
    "KFC - Roanne Mably",
    "Triangle - Evreux La Madeleine",
    "Intermarché - Evreux Netreville",
    "Intermarché - Ivry-la-Bataille",
    "Intermarché Super - Saint-Jean",
    "Mathimo - Bourgoin-Jallieu",
    "Intermarché - Castelnau-d'Estrétefonds",
    "Basic Fit - Martigues",
    "Intermarché - Rouxmesnil-Bouteilles",
    "Intermarché - Rouen Jardin des plantes",
    "KFC - Saint Etienne Villars",
    "KFC - Saint Etienne Meons",
    "Intermarché - Bergerac",
    "Système U - Saint-Laurent-d'Aigouze",
    "Parc Commercial du Luc - Moissac",
    "Bricorama - Viry-Noureuil",
    "Intermarché - Saint-André",
    "Intermarché - Corbas",
    "Intermarché - Rillieux-la-Pape",
    "Bricomarché - Estancarbon",
    "La Boucherie - Tarbes",
    "Centre Commercial la Peniche - Colmar",
    "Intermarché - Dieuze",
    "Intermarché Super - Villemandeur",
    "Darty - Hazebrouck",
    "Le Géant du Meuble - Cavagna Aubière",
    "Le Géant du Meuble - Sébazac",
    "Le Géant du Meuble - Cavagna Issoire",
    "Super U - Pierrefeu-du-Var",
    "Super U - Mareil-en-Champagne",
    "Intermarché Super Monteils (82)",
    "Intermarché Super - Montignac",
    "Intermarché Super - Sélestat",
    "Intermarché Super - Benfeld",
    "Supermarché Match - Fournes-en-Weppe",
    "Hotel-Restaurant Horizon Ath-Lessines",
    "Hotel & Aparthotel Casteau Mons - Soignies",
    "Ibis Styles - Marcq-en-Barœul",
    "Carrefour - Alès",
    "Intermarché - Saint-Vit",
    "Star Wash - La Chaize-le-Vicomte",
    "Bricomarché - Châlons-en-Champagne",
    "Intermarché - La Chapelle-Launay",
    "Mercure - Marcq-en-Barœul",
    "Relai Des Portes - Le Pian-Médoc",
    "Mr. Bricolage - Limoux",
    "Super U - Sainte-Menehould",
    "Stokomani -  Fontaine les Dijon",
    "Bricomarché - Bitche",
    "L'Orange Bleue - Valenciennes",
    "Netto - Lourdes",
    "Intermarché - Aigrefeuille-sur-Maine",
    "Mercure Chantilly",
    "Brit Hotel - Les Achards",
    "Bricorama Grenoble",
    "Ibis - Haguenau",
    "E.Leclerc - Chantonnay",
    "Contact Hotel - Kimotel Epone",
    "Super U - Valdahon",
    "Ibis - Gap",
    "Ibis Budget - Manosque",
    "Ibis - Villers-Saint-Paul",
    "Ibis Budget - Saint Etienne Stade",
    "Ibis - Cergy",
    "Centre Commercial - Orange les Vignes",
    "Ibis - Lyon Villefranche sur Saône",
    "Ibis Styles - Pertuis Luberon",
    "Picard - Orchies",
    "Ibis Budget - Macon Sud",
    "Super U - Lubersac",
    "Super U - Station-service Touvent",
    "Darty - Auray",
    "Intermarché - Le Pont-de-Beauvoisin",
    "Boulanger - Limonest",
    "Mobalpa - Champagne-au-Mont-d'Or",
    "Tacos&Co Grill - Valence",
    "Intermarché - Fronton",
    "Best Western - Belfort",
    "Ibis Budget - Senlis",
    "Ibis - Mont Saint Michel",
    "Ibis Styles - Mâcon",
    "Kyriad - Belfort Centre Gare",
    "Maison Rouge - Strasbourg",
    "Novotel - Lille Aéroport",
    "Intermarché - Bannalec",
    "Mercure Compiègne",
    "Hostellerie Saint Vincent - Beauvais",
    "Ibis Styles - Dreux",
    "Intermarché - Tulle",
    "Ibis Styles - Montargis Arboria",
    "Ibis Budget - Issoire",
    "Ibis Styles Auxerre (89)",
    "Kyriad - Clermont-Ferrand-Sud La Pardieu",
    "greet Hotel - Montbéliard",
    "Campanile - Pujols",
    "Ibis - Horbourg-Wihr",
    "Ibis Budget - Lons-le-Saunier",
    "Hôtel Première Classe - Annecy Cran Gevrier",
    "Ibis Styles - Villeneuve-sur-Lot",
    "Hôtel Restaurant Les Genêts - Bayonne",
    "Kyriad Blois",
    "Ibis Styles - Chambray-lès-Tours",
    "Ibis Budget - Poitiers Sud",
    "KFC - Bourges",
    "La Boucherie - Gauchy",
    "Mr. Bricolage - Alès",
    "La Boucherie - Epagny Metz-Tessy",
    "Super U - Riedisheim",
    "Bricomarché - Luxeuil-les-Bains",
    "Intermarché - Montbéliard",
    "Super U - Neuve-Église",
    "Bricomarché Saint Florent sur Cher",
    "Intermarché - Guérande",
    "Intermarché - Trémuson",
    "Bricomarché - Fismes",
    "Hotel Campanile - Metz Nord",
    "U Utile - Homps",
    "Domaine de Marlioz - Aix-les-Bains",
    "Holiday Inn - Strasbourg Sud",
    "Supermarché Match - Achenheim",
    "Super U - Prades",
    "Bricomarché - Châtillon-sur-Indre",
    "Restaurant 3 Brasseurs - Arras",
    "Sport 2000 - Firminy",
    "Super U - Russ",
    "Mr. Bricolage - Issenheim",
    "Mr. Bricolage - Colmar",
    "Mr. Bricolage - Bollwiller",
    "Intermarché - Auxon",
    "Super U - Aimargues",
    "Kiabi - Barentin",
    "Poltronesofa - Aubière",
    "123 Pare-Brise - Wittenheim",
    "Super U - Montrabé",
    "Intermarché - Saint-Malo, Rocabey",
    "Intermarché - Peymeinade",
    "Brit Hotel - Périgny",
    "Intersport - Auray",
    "Best Western - Baldersheim",
    "Super U - Brunstatt-Didenheim",
    "Contact Hotel - Colmar",
    "Intermarché - Bapaume",
    "Ibis Styles - Chartres",
    "La Boucherie - Saint-Dizier",
    "Brit Hotel - Pau",
    "Ibis - Lille Lomme Centre",
    "Intermarché - Arzon",
    "KFC - Andrézieux",
    "Brit Hotel - Tours",
    "Ibis Budget - Grésy-sur-Aix",
    "Ibis Budget Augny",
    "Super U - Martres-Tolosane",
    "Intermarché La Redorte (11)",
    "Mercure - Lyon Chaponnay",
    "Intermarché - Orry-la-Ville",
    "Intermarché - Gauchy",
    "Intermarché - Ribemont",
    "Intermarché Super - Saint-Quentin",
    "Intermarché - Chauny",
    "Ibis - Saint-Malo",
    "Bricomarché - Ernée",
    "Intermarché - Pollestres",
    "KFC - Arles",
    "KFC - Nîmes",
    "Mr. Bricolage - Pont-Saint-Esprit",
    "McDonald's - Thionville",
    "Chaussea - Montivilliers",
    "Kiabi - Faches-Thumesnil",
    "KFC - Rivesaltes",
    "Kiabi - Besançon",
    "Ibis - Chaintré",
    "Super U - Ille-sur-Têt",
    "Super U - Eaunes",
    "Intermarché - Caussade",
    "Intermarché - Le Louroux Beconnais",
    "Ibis Styles - Avignon Sud",
    "Intermarché - Isigny-sur-Mer",
    "Brit Hotel - Perpignan",
    "Mr. Bricolage - Saint-Dié-des-Vosges",
    "Mr. Bricolage - Lanester",
    "Ibis Budget - Nantes Nord Saint Herblain",
    "Ibis - Couëron",
    "Mr. Bricolage - Saint-Romain-de-Colbosc",
    "Buffalo Grill - Pontarlier",
    "Super U - Sennecey-lès-Dijon",
    "Intersport - Clermont-Ferrand",
    "Intermarché - Labruguière",
    "Super U - Briey",
    "Intermarché Super - Villecresnes",
    "Brit Hotel - La Chapelle-Saint-Luc",
    "Norauto - Le Crès",
    "Intermarché - Mirebeau-sur-Bèze",
    "Super U - Les Achards",
    "Intermarché - Massiac",
    "Super U - Saint-Germain",
    "Super U - Lemud",
    "Super U - Hambach",
    "Super U - Joinville",
    "Clinique Esquirol Saint Hilaire ELSAN - Agen",
    "Mondial Tissus - Perpignan",
    "Mondial Tissus - Cholet",
    "Ibis - Fleurus",
    "Ibis Budget - Charleroi",
    "IBIS SERAING",
    "Cayman - Charleroi Airport",
    "Nice Valley - Nice",
    "Restaurant Léon - Vandœuvre-lès-Nancy",
    "Super U - Essert",
    "Lavage Auto Hygie Cars - L'Isle-d'Espagnac",
    "Intermarché - Saint-Lys",
    "Super U - Nogent",
    "Super U - Thaon Les Vosges",
    "Mercure - Lyon L'Isle-d'Abeau",
    "Super U - Fontoy",
    "KFC - Perpignan",
    "Contact Hotel - Aurillac",
    "Novotel - Blois",
    "Bricomarché St Romain en Viennois",
    "Super U - Alès",
    "Intermarché - Rezé",
    "Restaurant 3B Avranches - Le Val-Saint-Père",
    "Laverie Speed Queen - Montauban",
    "Système U - Pineuilh",
    "Mairie - Fouras",
    "Mr. Bricolage - Champniers",
    "Intermarché - Pont-à-Mousson",
    "Action - Verneuil d'Avre",
    "Intermarché - Bain-de-Bretagne",
    "Super U - Saint-Pol-de-Léon",
    "Système U - Maxéville",
    "Super U - Lanmeur",
    "Leon de Bruxelles - Bourges",
    "greet hotel Orthez Bearn - Biron",
    "Super U - Montigny-lès-Metz",
    "Super U - Talange",
    "Super U - Châtenois",
    "Super U - Liffol-le-Grand",
    "Brit Hotel - Rouen",
    "Netto - Beauzelle",
    "Mr Bricolage Saint Clément (89)",
    "Mr. Bricolage - Borgo",
    "Intermarché - Morhange",
    "Système U - Saint Brice en Cogles",
    "Mr. Bricolage - Castres",
    "Carrefour - Belfort-Andelnans",
    "Carrefour - Mulhouse-Dornach",
    "Carrefour - Montbéliard",
    "Carrefour - Haguenau",
    "Carrefour - Dorlisheim",
    "Carrefour - Villers-Semeuse",
    "Carrefour - Soissons",
    "Carrefour - Auxerre-Monéteau",
    "Carrefour - Saint-Jouan-des-Guérets",
    "Carrefour - Caen-Rots",
    "Carrefour - Garges-lès-Gonesse",
    "Carrefour - Creil-Saint-Maximin",
    "Carrefour - Livry-Gargan",
    "Carrefour - Dreux",
    "Carrefour - Sarrebourg",
    "Carrefour - Verdun",
    "Carrefour - Sainte-Marie-aux-Chênes",
    "Carrefour - Mondelange",
    "Carrefour - Grosbliederstroff",
    "Carrefour - Nancy Houdemont",
    "Carrefour - Vesoul",
    "Carrefour - Toul",
    "Carrefour - Remiremont",
    "Carrefour - Dole",
    "Carrefour - Lunéville",
    "Carrefour - Perrigny-lès-Dijon",
    "Carrefour - Wattignies",
    "Carrefour - Bruay-la-Buissière",
    "Carrefour - Courrières",
    "Carrefour - Saint-Quentin",
    "Carrefour - Villeneuve-d'Ascq-Flers",
    "Carrefour - Cambrai-Proville",
    "Carrefour - Colmar",
    "Carrefour - Essey-lès-Nancy",
    "Carrefour - Moulins-lès-Metz",
    "Ibis Budget - Villeneuve-d'Ascq",
    "Ibis La Louvriere",
    "Ibis Nivelles",
    "Carrefour Market - Bourg-Achard",
    "Novotel - Perpignan Nord Perpignan",
    "Intersport - Saint-Paul-lès-Dax",
    "Intermarché - Noirétable",
    "Ibis - Perpignan",
    "Mr. Bricolage - Paray-le-Monial",
    "Centrakor - L'Aigle",
    "Carrefour Market - Bordeaux",
    "Système U - Sarralbe",
    "Système U - Diemeringen",
    "Maison de la Presse Tabac Arago - Albi",
    "Mercure - Chanas",
    "Mr. Bricolage - Lillebonne",
    "La Boucherie - Morlaix",
    "Bricomarché - Carhaix-Plouguer",
    "Netto - Troyes",
    "Intermarché - Troyes",
    "Intermarché Super - Saint-Julien-les-Villas 2",
    "Intermarché Super - Saint-Julien-les-Villas 1",
    "Action - Rosières-près-Troyes",
    "Basic Fit - Les Pennes-Mirabeau",
    "Basic Fit - Caussade",
    "Basic Fit - Saint-Germain-lès-Corbeil",
    "Basic Fit - Angoulême",
    "Basic Fit - Héricourt",
    "Basic Fit - Montargis",
    "Basic Fit - Paray-le-Monial",
    "Système U - Faulquemont",
    "Système U Oeting (57)",
    "E.Leclerc - La Flèche",
    "Centre Commercial La Pardieu - Clermont-Ferrand",
    "Roady - Belleville-en-Beaujolais",
    "Intermarché Le Bugue (24)",
    "Mr. Bricolage - Hazebrouck",
    "Mr. Bricolage - Annœullin",
    "Mr. Bricolage - Armentières",
    "E.Leclerc - Achères",
    "Ô Délices food - Montech",
    "Intermarché - Véretz",
    "McDonald's - L'Isle-d'Abeau",
    "Intermarché - Pugnac",
    "But - Mende",
    "Mr. Bricolage - Dombasle-sur-Meurthe",
    "K9 Station Service - La Garde",
    "Système U - Saint-Python",
    "Le Bouche à Oreille - Boutervilliers",
    "Cora Charleroi",
    "Cora - Hornu",
    "Cora - Rocourt",
    "Cora - Messancy",
    "Cora - Woluwe",
    "Cora - Anderlecht (Be)",
    "Cora - La Louvière",
    "Centre Commercial Maine Street Super U - Ruaudin",
    "Carré D'Or - Perpignan",
    "Carré d'or Perpignan 2",
    "Carré d'or Perpignan 3",
    "Carré d'or Perpignan 4",
    "Système U - Anould",
    "E.Leclerc - Perpignan Espace Polygone",
    "E.Leclerc - Espace Perpignan Sud",
    "Aldi - Épinay-sous-Sénart",
    "Super U - Pluvigner",
    "Intermarché - Écrouves",
    "Speed Park - Hénin-Beaumont",
    "Kiabi - Saint-Quentin",
    "Kiabi - Orléans",
    "Action - Aubenas",
    "Système U  Algrange",
    "Station U - Algrange",
    "Super U - Saint-Laurent-en-Grandvaux",
    "Mr. Bricolage - Les Hauts-d'Anjou",
    "Mr. Bricolage - Auch",
    "Lumicenter - Sébazac-Concourès",
    "Esso - Saint-Geours-de-Maremne",
    "Besson Chaussures - Saint-Memmie",
    "Carrefour - Blois",
    "Carrefour - Évreux",
    "Carrefour - Metz-Technopôle",
    "Société Générale - Brive-la-Gaillarde",
    "Top Office - Chambray-lès-Tours",
    "Intermarché - Is-sur-Tille",
    "ACE Hôtel Paris - Sud Villabé",
    "Super U - Saint-Germain-du-Bois",
    "Société Générale - La Destrousse",
    "Garage Renault Dacia - La Destrousse",
    "La vie Claire - La Destrousse",
    "Le Saint-Jean - Saint-Jean-de-Soudain",
    "Weldom La Tour du Pin - Saint-Clair-de-la-Tour",
    "Intersport - Le Pont-de-Beauvoisin",
    "Boulangerie Feuillette - Angers",
    "Boulangerie Feuillette - Bourges",
    "Intermarché - Dax",
    "Action - Maromme",
    "Action - Viry-Noureuil",
    "Cuir Center - Longueau",
    "Action - Saint-Pierre-en-Auge",
    "Action - Rue",
    "Action - Sains-en-Gohelle",
    "Action - Albert",
    "Action - Neufchâtel-en-Bray",
    "Action - Sainte-Austreberthe",
    "Auchan - Villers-Bretonneux",
    "Brassier Le Carré Blanc - Saint-Herblain",
    "Super U - Pont-Croix",
    "KFC - Anthy-sur-Léman",
    "Système U - Le Pontet",
    "Carrefour Market - Salles",
    "Intermarché Sigean (11)",
    "Darty - Bergerac",
    "Intermarché - Yzosse",
    "Intermarché - Saint-Paul-lès-Dax",
    "Ibis - Beziers",
    "Novotel - Montpellier",
    "Super U - Merville",
    "Hyper U - Brie-Comte-Robert",
    "Intermarché - Concarneau",
    "Mr Bricolage Craponne (69)",
    "Mr. Bricolage - Châtillon-sur-Chalaronne",
    "Mr. Bricolage - Migennes",
    "Ibis Budget - Pouilly-en-Auxois",
    "Jardiland - Brive",
    "Jardiland - Carcassonne",
    "Jardiland - Evreux",
    "Gamm Vert - Tavers",
    "Gamm Vert - Le Controis-en-Sologne",
    "Hippo Wash - Cherbourg-en-Cotentin",
    "Super U - Bernolsheim",
    "Novotel - Saint-Jean-de-Braye",
    "Novotel - Boves Amiens",
    "Logis Hôtel Cottage - Calais",
    "Ibis Budget - Romorantin-Lanthenay",
    "Ibis Budget - Saran (Orléans Nord)",
    "Ibis Budget - Libourne",
    "Carrefour Market - Mimizan",
    "Intermarché - Ploërmel",
    "hotelF1 - Glisy",
    "hotelF1 - Saint-Cergues",
    "hotelF1 - Beauvais",
    "hotelF1 - Brétigny-sur-Orge",
    "hotelF1 - Chambéry",
    "hotelF1 - Chaumont",
    "hotelF1 - Chilly-Mazarin",
    "hotelF1 - Cholet",
    "hotelF1 - Clermont Ferrand",
    "hotelF1 - Évry-Courcouronnes",
    "hotelF1 - Angoulins-sur-Mer",
    "hotelF1 - Saint-Saturnin",
    "hotelF1 - Les Ulis",
    "hotelF1 - Villeneuve-d'Ascq",
    "hotelF1 - Limoges",
    "hotelF1 - Saint-Priest",
    "hotelF1 - Solaize",
    "hotelF1 - Oullins",
    "hotelF1 - Perpignan",
    "hotelF1 - Saint-Étienne-du-Rouvray",
    "hotelF1 - Saint-Étienne",
    "hotelF1 - Trignac",
    "hotelF1 - Thonon Les Bains",
    "hotelF1 - Vannes",
    "hotelF1 - Villemomble",
    "Hotel F1 Ecuelles (77)",
    "Ibis - Evry",
    "Ibis Budget - Lille Wasquehal",
    "Ibis Budget - Mougins",
    "NOVOTEL ANNECY",
    "SOFITEL BIARRITZ",
    "Ibis Budget Villenave D'Ornon (33)",
    "Ibis Budget - Marseille La Valentine",
    "Hôtel ibis Nanterre La Défense (92)",
    "Novotel Paris Gare de Lyon",
    "Hôtel Mercure Paris Massy Gare",
    "Hôtel Mercure Paris Orly Tech",
    "bis Paris Tour Eiffel Cambronne",
    "Basic Fit - Roquevaire",
    "Supeco - Roquevaire",
    "Intermarché - La Destrousse",
    "Retail Park - Dreux",
    "Retail Park - Saint-Pierre-lès-Nemours",
    "Retail Park - Vert-Saint-Denis",
    "Sofitel - Quiberon",
    "Hotel F1 Blagnac (31)",
    "Restaurant la mie CÂLINE - Sorgues",
    "Mercure - Orléans",
    "Ibis Budget - Meung-sur-Loire",
    "Super U - Gergy",
    "Roady - Perreux",
    "Intermarché - Quessoy",
    "Mr. Bricolage - Laroque-des-Albères",
    "Jacques Bana Coiffure - Saint-Mitre-les-Remparts",
    "Ibis Budget - Saint-Lô",
    "Hyper U - Colmar",
    "Super U - Arc-sur-Tille",
    "Buffalo Grill - Amnéville",
    "Carrefour - Reims Cormontreuil",
    "Mr. Bricolage - Moncel-lès-Lunéville",
    "Intermarché - Moyenmoutier",
    "Action - Lebetain",
    "MGALLERY AIX EN PROVENCE",
    "Bricomarché Aire Sur L'Adour (40)",
    "Intermarché - Néris-les-Bains",
    "Centre Commercial Les Tisserands - Louviers",
    "Intermarché - Servas",
    "Mr. Bricolage - Poitiers",
    "77 La boitardière - Amboise",
    "Action - Bourgueil",
    "Cora - Mondercange (Lux)",
    "Carrefour - Lens 2",
    "Bricopro Bricolage - Saint-Laurent-de-la-Salanque",
    "La Cage Brasserie Sportive - Bègles",
    "Intermarché - Bourg-en-Bresse",
    "Super U - Rezé",
    "CoMarché - Braine-le-Comte",
    "Lidl - Brioude",
    "Bio-Planet - Gembloux",
    "Univers Bois - Varetz",
    "Intermarché - Canet-en-Roussillon",
    "E.Leclerc - Loudun",
    "Bricomarché Pruniers en sologne",
    "Super U - Fonbeauzard",
    "Intermarché - Plaisance-du-Touch",
    "Orchestra - Saint-Égrève",
    "Action - Bergerac",
    "Buffalo Grill - Sarrebourg",
    "Chaussea - Échirolles",
    "Action Callian",
    "V&B Sarrebourg (57)",
    "Holding Paris Metz Miramas (13)",
    "Restaurant Le Boeuf Sur Grill - Igny",
    "Biocoop - Mont-de-Marsan",
    "Action - Carcassonne",
    "Action - Cholet",
    "Action - Lunéville",
    "Darty Buhl-Lorraine (57)",
    "Action - Monéteau",
    "Ibis - Mouilleron-le-Captif",
    "L'Antre Frères - Saint-Méloir-des-Ondes",
    "Intermarché - Le Lude",
    "Bricomarché - Riom",
    "Bricomarché - Issoudun",
    "Espace Commercial Planfoy (42)",
    "Magasin Envia Cuisine - Bruay-la-Buissière",
    "Spar - Fitou",
    "Intermarché - Rambervillers",
    "Intermarché - Buc",
    "E.Leclerc - Montauban",
    "Intermarché - Guémené-sur-Scorff",
    "Ibis Budget - Isneauville",
    "Best Western - Trignac",
    "Briconautes - Saint-Cyprien",
    "Super U - Toul",
    "BDM Gonesse",
    "NEF - Le Havre",
    "BDM Le Hvare Utopia",
    "BDM Nanteuil les Meaux (77)",
    "BDM SERRIS",
    "Ibis - Calais",
    "Ibis - Danjoutin",
    "Mr. Bricolage - Saint-Junien",
    "Centre Commercial Carrefour - Venette",
    "U Express - Nieul",
    "Ibis - Toulouse Purpan",
    "Ibis Budget - Cosne-Cours-sur-Loire",
    "Bricomarché - Cussac",
    "Lavage Label Bulle - Golbey",
    "Super U - Montgeron",
    "Hôtel Saint-Fons",
    "Ibis - Mellac",
    "Intermarché - Elne",
    "Atelier du lavage  Beauvais",
    "Restaurant La Pataterie - Trégueux",
    "Au Bureau - Pontarlier",
    "Carrefour Contact Bucey les Gy",
    "Gamm Vert - Gan",
    "Gamm Vert & Mr. Bricolage - Cambo",
    "Gamm Vert & Mr. Bricolage - Hasparren",
    "Gamm Vert - Oloron",
    "Gamm Vert - Tarbes",
    "Gamm Vert - Lourdes",
    "Mr. Bricolage - Hendaye",
    "Chaussea - Saumur",
    "Chaussea - Trignac",
    "Chaussea - Valleroy",
    "Chaussea - Bruay-la-Buissière",
    "Chaussea - Chenôve",
    "Chaussea - Essey-lès-Nancy",
    "Chaussea - Évreux",
    "Chaussea Istres (13)",
    "Chaussea - Moncel-lès-Lunéville",
    "Chaussea - Perpignan",
    "Parc Commercial de la Frugière - Privas",
    "Une Tartine De Bonheur - Le Loroux-Bottereau",
    "Action - Villefranche-de-Rouergue",
    "Burger King - La Sentinelle",
    "Match Tourcoing Mercure (59)",
    "Supermarché Match - Dunkerque",
    "Match Lille Halles Solferino (59)",
    "Supermarché Match - Calais, Lafayette",
    "Match Villeneuve d'Ascq le Sart (59)",
    "Supermarché Match - Villeneuve d'Ascq Cousinerie",
    "Supermarché Match - Douai, Kiosque",
    "Match Marcq-En-Baroeul (59)",
    "Supermarché Match - Huningue",
    "Match Henin-Beaumont (62)",
    "Supermarché Match - Pont-à-Mousson",
    "Supermarché Match - Champigneulles",
    "Supermarché Match - Oignies",
    "Supermarché Match - Saverne",
    "Supermarché Match - Lannoy",
    "Supermarché Match - Lambersart (Dunkerque)",
    "Supermarché Match - Charleville-Mézières",
    "Match Hayange (57)",
    "Carrefour Market - Pont-l'Abbé-d'Arnoult",
    "Supermarché Match - Thann",
    "Supermarché Match - Tourcoing (Fleurus)",
    "Supermarché Match - Arras",
    "Supermarché Match - Jarny",
    "Supermarché Match - Villerupt",
    "Match Cernay (68)",
    "Supermarché Match - Wissembourg, Pepinière",
    "Match Hochfelden (67)",
    "Match Reichshoffen (67)",
    "Supermarché Match - Deûlémont",
    "Supermarché Match - Wambrechies",
    "Supermarché Match - Ronchin",
    "Supermarché Match - Wattrelos Abattoir",
    "Supermarché Match - Bischheim",
    "Supermarché Match - Armentières",
    "Brit Hotel Le Vesoul - Pusey",
    "Action - Augny",
    "Chaussea - Hirson",
    "Escatel Hotel - Mâcon",
    "Supermarché Match - Jœuf",
    "Super U - Léognan",
    "Supermarché Match - Yutz",
    "Match Ars (57)",
    "Mairie de Gauchy - Place des Clos",
    "Supermarché Match - Grenay",
    "Mairie de Gauchy - Salle Polyvalente",
    "Match Wasselonne (67)",
    "La Boucherie Castelnau Le Lez",
    "Supermarché Match - Wissembourg Peupliers",
    "Supermarché Match - Douai (Warenghien)",
    "Grand Frais - Chasseneuil-du-Poitou",
    "Supermarché Match - La Madeleine",
    "Supermarché Match - Neufchâteau",
    "GAMM VERT DAVEZIEUX",
    "Supermarché Match - Thaon-les-Vosges",
    "Gamm Vert Montélimar",
    "Supermarché Match - Chalons Chanzy",
    "Gamm Vert Pierrelatte",
    "Boulangerie Jeanne - Charmes",
    "Supermarché Match - Cucq",
    "Intermarché - L'Union",
    "Supermarché Match - Commercy (Rue d'Euville)",
    "Supermarché Match - Saint-Max",
    "Atelier Du Lavage Neuilly En Thelle",
    "Supermarché Match - Dieuze",
    "4 Pieds Coignieres",
    "Supermarché Match - Calonne-Ricouart",
    "Match Bouxwiller (67)",
    "Supermarché Match - Lure",
    "Supermarché Match - Commercy (Morelle)",
    "Supermarché Match - Charmes",
    "Supermarché Match - Rambervillers",
    "Supermarché Match - Doullens",
    "Boulangerie Louise - Trie-Château",
    "Supermarché Match - Morhange",
    "Nouveau Panier Frais Epone",
    "Supermarché Match - Soultz-sous-Forêts",
    "Match Niederbronn-Les-Bains (67)",
    "Match Wervicq-Sud (59)",
    "Espace Commercial Alpha - Colmar",
    "Supermarché Match - Vieux-Condé",
    "Netto - Soustons",
    "Supermarché Match - Saint-Amand",
    "Match Bouzonville (57)",
    "Intermarché Figeac (46)",
    "Supermarché Match - Le Quesnoy",
    "Intermarché - Rouffach",
    "Supermarché Match - Avesnelles",
    "Supermarché Match - Cysoing",
    "Supermarché Match - Avesnes-les-Aubert",
    "Intermarché Bréval (78)",
    "Intermarché - Pacy-sur-Eure",
    "Marché Frais - Orgeval",
    "Match Puttelange-Aux-Lacs (57)",
    "Best Western - Tonnay-Charente",
    "Fonciariane Saulx-les-Chartreux (91)",
    "Castorama - Fleury-sur-Orne",
    "Fonciariane Saint-André-les-Vergers (10)",
    "Fonciariane Taverny (95)",
    "Fonciariane Flins-sur-Seine - Lot G3 (78)",
    "Fonciariane Flins-sur-Seine - Lot F2 (78)",
    "Zolpan - Saint-Parres-aux-Tertres",
    "Intermarché - Jarny",
    "Picard - Groslay",
    "Chaussea - Val de Briey",
    "Aldi Athis Mons (91)",
    "Chaussea - Sainte-Marie-aux-Chênes",
    "Chaussea Thionville (57)",
    "Chaussea - Briey",
    "Carrefour - Saint-Dizier",
    "Chaussea - Neufchateau",
    "Chaussea - Reims Cormontreuil",
    "Centre Commercial - Marconne",
    "Carrefour Market - La Monnerie-le-Montel",
    "Intermarché - Pont-du-Château",
    "Mr. Bricolage - Savenay",
    "Super U - Veynes",
    "Mon Brico - Saint-Fulgent",
    "Mon Brico - Mauléon",
    "Mon Brico - Mortagne",
    "Mon Brico - Bressuire",
    "Mon Brico - Thouars",
    "Mon Brico - Sauzé-Vaussais",
    "Mon Brico - La Châtaigneraie",
    "Mon Brico - Chantonnay",
    "Super U - Saint-Seurin-sur-l'Isle",
    "Super U - Saint-Médard-de-Mussidan",
    "U Express - Saint-Arnoult",
    "Intermarché - Gray",
    "Biocoop du Rouennais Amfreville La Mi Voie (76)",
    "Restaurant Chez Le Brasseur - Sainte-Eulalie",
    "Kfc Saint-Witz (95)",
    "Shopping Promenade - Arles",
    "Carré Sud - Nîmes",
    "Frey Claye Souilly (77)",
    "Shopping Promenade Coeur Alsace - Reichstett",
    "Carrefour - Longeville-lès-Saint-Avold",
    "Orange Bleue - Valence d'Agen",
    "La Boucherie - Saint-Jean-de-Védas",
    "E.Leclerc - Libourne",
    "Best Western - Guérande",
    "Big Mat - Bastia",
    "Intermarché Louviers (27)",
    "Bricomarché - Nivillac",
    "Bricomarché - Graulhet",
    "Netto - La Réole",
    "Mr Bricolage Folelli (20)",
    "Intermarché - Le Pouliguen",
    "Action - Noyon",
    "Carrefour - Reims Neuvillette",
    "Action Niort (79)",
    "Action - Angoulême",
    "Dégriffstock - Portet-sur-Garonne",
    "Restaurant Fujin - Portet-sur-Garonne",
    "Fonciariane Flins-sur-Seine - Lot G1 (78)",
    "Ibis Budget - Dunkerque",
    "Burger King - Dreux",
    "But Seclin",
    "Action - Annemasse",
    "NEF - Le Havre 2",
    "Lidl - Gonesse 1",
    "Kyriad Roanne",
    "Ibis Styles Besancon (25)",
    "Gamm Vert - Saint-Julien-l'Ars",
    "Maison du Monde - Pamiers",
    "Action - Carhaix-Plouguer",
    "Aquavert Francheville",
    "Picard - Rambouillet",
    "Sofitel Quiberon (56)",
    "hotelF1 - Ecuelles",
    "Jardiland - Groslay",
    "La Cartonnerie - Dammarie-les-Lys",
    "Super U - Gérardmer",
    "Valmont Primeurs Pomchou - La Ville-du-Bois",
    "Résidence Le Catalogne - Amélie-les-Bains-Palalda",
    "Auchan - Jouy-en-Josas",
    "Librefruit Magny en Vexin (95)",
    "Immobiliere Franchitti Ormoy",
    "Immobiliere Franchitti Saint Fargeau",
    "KFC - Neuilly-sur-Marne",
    "Kyriad - Vineuil",
    "Jardiland - Châlons-en-Champagne",
    "Jardiland - Dadonville",
    "Jardiland - Avranches",
    "Jardiland - Coutances",
    "Jardiland - Granville",
    "Jardiland - Saint-Lô",
    "Gamm Vert Vallet",
    "Specialized Store - Condom",
    "Magasin Satoriz - Échirolles",
    "Retail Park - Flers",
    "Le Palais d'Emeraude - Vire-Normandie",
    "Intermarché - Montech",
    "Mr. Bricolage - Montauban",
    "Mr. Bricolage - Pamiers",
    "U Express - Monteux",
    "Basic Fit - Saint-Sulpice-sur-Risle",
    "Bricorama - Limoges",
    "Basic Fit - Jeuxey",
    "Basic Fit - Bessoncourt",
    "Mr. Bricolage - Bias",
    "Netto - Bégard",
    "Action - Plerin",
    "Intersport Saint Genis Pouilly (01)",
    "Netto - Lannion",
    "Librefruit - Gisors",
    "Ibis Budget - Quimper",
    "La Boucherie - Saint-Laurent-des-Vignes",
    "Jardiland - Tours",
    "Gamm Vert Le Loroux Bottereau",
    "Decathlon - Montélimar",
    "Satoriz - Blotzheim",
    "Ibis Budget - Redon",
    "Intermarché - Marnay",
    "Centre Commercial de l'Ancre Marine - La Ciotat",
    "Intermarché - Plomodiern",
    "Intermarché  Rostrenen",
    "Story - Angers",
    "Buffalo Grill - Saint-Dizier",
    "Buffalo Grill - Pont-À-Mousson",
    "Action - Savigny-le-Ranger Nancyle",
    "Zone Commerciale Andelat (15)",
    "Retail Park - Montauban",
    "Match Bavay (59)",
    "Match Longwy (54)",
    "Action - Loison-sous-Lens",
    "Keepcool Firminy - Unieux",
    "Action - Auchel",
    "Carrefour - Saint-Dié-des-Vosges",
    "Supermarché Match - Maubeuge",
    "La Foir'Fouille - Bergerac",
    "Action - Bourg-en-Bresse",
    "Stockobox - Léguevin",
    "Quick Douai - Férin",
    "Sogenial - Quick Villeneuve Saint Georges (94)",
    "ALDI - Reims Cormontreuil",
    "Del Arte - Avranches",
    "Retail Park Grand Frais - Azay-le-Rideau",
    "Jour de Fête - Bessoncourt",
    "Intermarché - Llupia",
    "Bricomarché - Lavaur",
    "E.Leclerc - Cholet",
    "Carrefour Contact - Lacanau",
    "Carrefour Market - Hourtin",
    "Carrefour Contact - Carcans",
    "Carrefour Contact Lège-Cap-Ferret",
    "Basic Fit - Lure",
    "Basic Fit Holfim Puygouzon",
    "Basic Fit - Tergnier",
    "Basic Fit - Guipry-Messac",
    "Basic Fit - Le Trait",
    "Aldi Holfim Fos-sur-mer (13)",
    "Carrefour Contact Vendays Montalivet (33)",
    "SCI - Malemort",
    "Intermarché - Vieillevigne",
    "Netto - Saint-Quentin",
    "E.Leclerc - Quéven",
    "Arches Metropole - Saint-Dizier",
    "We Are Select Givors (69)",
    "Intermarché - Vireux-Molhain",
    "La Boucherie - Laon",
    "Mr. Bricolage - Arc-lès-Gray",
    "Aldi - Boé",
    "Action - Louhans",
    "Intermarché - Fains-Véel",
    "Super U - Frignicourt",
    "Bricorama Sébazac-Concourès",
    "Bricomarché - Segré",
    "Mr. Bricolage - Davézieux",
    "Jardiland - Guéret",
    "Jardiland La Queue En Brie (94)",
    "Jardiland - Saint-Germain-du-Puy",
    "Jardiland - Saint-Pierre-du-Mont",
    "Jardiland - Soyaux",
    "Jardiland Trelissac (24)",
    "Gamm Vert Dax",
    "Match Guenange (57)",
    "Gamm Vert Hagetmau",
    "Gamm Vert - Morcenx",
    "Match Niedermodern (67)",
    "Supermarché Match - Pérenchies",
    "Match Saint Avold (57)",
    "Mr. Bricolage - Saint-Jouan-des-Guérets",
    "Match Schirmeck (67)",
    "Supermarché Match - Selestat",
    "Gamm Vert - Soustons",
    "Gamm Vert - Orthez",
    "Supermarché Match - Dombasle",
    "Urban Soccer - Pessac",
    "Restaurant Canopée Café Mérignac (33)",
    "Intermarché - Prayssac",
    "Sport 2000 - Saint-Sauveur-d'Aunis",
    "Gamm Vert - Sorbiers",
    "Parc Commercial de la Jaufertie - Soyaux",
    "Intermarché - Donges",
    "Mr. Bricolage - Hagetmau",
    "Intermarché - Roquefort",
    "Jardiland - Agen",
    "Jardiland - Champniers",
    "Supermarché Match - Château Salins",
    "Jardiland - Chenôve",
    "Action - Châlette-sur-Loing",
    "Buffalo Grill - Saran",
    "Ibis Styles - Crolles",
    "KFC Holfim Montpellier (34)",
    "Zac De La Crête Breteville Sur Odon",
    "KFC - Abbeville",
    "Carl's Jr. - Le Pontet",
    "Quick - Lanester",
    "La Boucherie - Vannes",
    "Burger King Bernolsheim (67)",
    "Supermarché Match - Auberchicourt",
    "Le Moulin Duppigheim (67)",
    "GIFI - Vendenheim",
    "Valimmo Mougins (HUB N°1) - Mougins",
    "Soccer - Mougins",
    "Big Sky Hotel & Spa - Chamonix",
    "Gamm Vert - La Roche-sur-Yon",
    "Gamm Vert - Chantonnay",
    "Gamm Vert - Fontenay-le-Comte",
    "Gamm Vert - Challans",
    "Cinéville - Vannes",
    "Cinéville - La Roche-sur-Yon",
    "Cinéville - Vern-sur-Seiche",
    "Cinéville - Saint-Sébastien-sur-Loire",
    "Cinéville - Hénin-Beaumont",
    "Cinéville - Concarneau",
    "Buffalo Grill Saint Agathon (22)",
    "Buffalo Grill - Lannion",
    "Basic Fit - Villers-Cotterêts",
    "Nivana Chatuzange Le Goubet",
    "First Grill 45 - La Chapelle-Saint-Mesmin",
    "La Petite Villette - Cholet",
    "Netto - Graulhet",
    "Ibis - Essômes-sur-Marne",
    "Overheads Belgium",
    "Restaurant La Villa Bersol - Gradignan",
    "KFC - Essey-lès-Nancy",
    "Intermarché Puy L'Évêque (46)",
    "Marie Blachère - Alès",
    "Super U - Gertwiller",
    "Gouny & Starkley - Livry-Gargan",
    "Sport 2000 - Grenade",
    "Balladins - Villefranche-de-Rouergue",
    "Intersport - L'Aigle",
    "Ibis Styles - Beauregard",
    "Mr. Bricolage - L'Arbresle",
    "Boucherie Bayle - La Grand-Croix",
    "Ekosport Chambery Landiers (73)",
    "Marie Blachère - Chaponnay",
    "Subway - Vertou",
    "Action Cuers (83)",
    "Ekosport - Le Pontet",
    "Extansion Carrefour contact Tournay",
    "Biocoop - Cholet",
    "La Boucherie - Pamiers",
    "Astor Cogolin",
    "Intermarché Super - Moustajon",
    "Intermarché - Lombez",
    "Match Metz-Sablon (57)",
    "Kfc Goussainville (95)",
    "Ma Jardinerie - Illzach",
    "Ma Jardinerie - Wittenheim",
    "Ma Jardinerie Exincourt",
    "Ma Jardinerie Vesoul",
    "Ma Jardinerie Aubange",
    "Basic Fit - Avion",
    "Marie Blachère - Saint-Avold",
    "Marie Blachère - La Chapelle-Saint-Luc",
    "Marie Blachère - Amnéville",
    "Marie Blachère - Oyonnax",
    "Marie Blachère - Pontivy",
    "Marie Blachère - Rivières",
    "Marie Blachère Fos Sur Mer (13)",
    "Marie Blachère - Terrasson-Lavilledieu",
    "Marie Blachère - Briançon",
    "Marie Blachère Chalon Sur Saône (71)",
    "Marie Blachère - Lambres-lez-Douai",
    "Marie Blachère - Bellac",
    "Marie Blachère St Alban (31)",
    "Marie Blachère - Bagnols-sur-Cèze",
    "KFC - Beauvais",
    "Marie Blachère - Coublevie",
    "Boulangerie Feuillette - Lons",
    "Biocoop - Roncq",
    "Boulangerie Ange Roncq (59)",
    "Retail Park St Maximin (60)",
    "Intermarché - Longuyon",
    "Super U - Bans",
    "Magasin Satoriz - Epagny Metz-Tessy",
    "Action - Rivières",
    "Retail Park Issoire",
    "Supermarché Match - Malzéville",
    "Au Lotus Bleu - Péronne",
    "O'Tacos - Chambly",
    "KFC - Outreau",
    "KFC - Calais",
    "Ibis Waterloo (BEL)",
    "Marie Blachère - Maubeuge Jean Jaurès",
    "Marie Blachère - Forbach",
    "Espace Korzilius Colmar (68)",
    "Boulangerie Louise - Méru",
    "Marie Blachère - Uzes",
    "Marie Blachère - Lannion",
    "Marie Blachère - Freyming-Merlebach",
    "Marie Blachère Bédarieux (34)",
    "Marie Blachère - Bollene",
    "Marie Blachère Froideconche (70)",
    "Action Migennes (89)",
    "Retif - Augny",
    "Intermarché - Limoges",
    "Best Western - Sélestat",
    "Boulangerie Ange - Lunel",
    "Inter Caves - Pringy",
    "Chemin de la Plane - Cornebarrieu",
    "Boulangerie Charles Sanchez - Cornebarrieu",
    "Boulangerie Ange - Château-Thierry",
    "BBFD SCI BNB Saint Cyr (78)",
    "Atol - Castelculier",
    "BBFD - Henin Beaumont (62)",
    "BBFD - Saint Jean De La Ruelle (45)",
    "Boulangerie Feuillette - Gravigny",
    "Boulangerie Ange - Bettancourt-la-Ferrée",
    "BBFD - Trelissac (24)",
    "BBFD - REEF Limoges",
    "BBFD - Dammarie Les Lys (77)",
    "Action - Saint-Georges-sur-Loire",
    "Grand Frais - La Richardais",
    "Marie Blachère - Fécamp",
    "Stockomani - Montauban",
    "Epsilon Capital Sainte-Geneviève (91)",
    "Carrefour Market - Gembloux",
    "Carrefour - Montauban",
    "Le Plein - Roncq Cluster - Auchan",
    "Le Plein - Plaisir - Auchan",
    "Auchan - Le Mans Sud",
    "Le Plein - Les Martres-de-Veyre - Auchan",
    "Quick St Etienne (42)",
    "Ibis - Auray",
    "AD Delhaize - Bertrix",
    "Action Valserhône Securitest (01)",
    "Flunch - Charleville-Mézières",
    "Carrefour Market Pezenas (34)",
    "Zone Commerciale - Pézenas",
    "Cuir Center Jouy Aux Arches (57)",
    "Satoriz Albertville (73)",
    "Centre Commercial de L'Hippodrome - Aurillac",
    "Marie Blachère - Romilly-sur-seine",
    "Marie Balchere Romilly-Sur-Seine",
    "AD Delhaize - Les Bons Villers",
    "Zeeman - Arras",
    "Le Marché de Léopold - Langon",
    "Fournil 89 Vertaizon",
    "Darty - Villabé",
    "McDonald's - Villabé",
    "Lidl & McDonald's - Lesménils",
    "Lidl - Biganos",
    "Foir'Fouilles - Bourg-lès-Valence",
    "Jardiland Cormeilles-en-Parisis,",
    "Centre Commercial Parc des Drapeaux - Rots",
    "Retail Park Les Portes du Sud - Chalon-sur-Saone",
    "Retail Park des Bouchardes - Crêches-sur-Saone",
    "Super U - L'Horme",
    "Restaurant Atlantis - Reims Cormontreuil",
    "Grand Frais - Brives-Charensac",
    "Stokomani - Bourgoin-Jallieu",
    "But - Houdemont",
    "Grand Frais - L'Isle-d'Abeau",
    "Grand Frais - Guyancourt",
    "Grand Frais - La Teste-de-Buch",
    "Grand Frais - Chasse-sur-Rhône",
    "Grand Frais - Nîmes",
    "Grand Frais - Le Cannet",
    "Côté Halles - Clermont-Ferrand",
    "Grand Frais - Seyssins",
    "Grand Frais - Annecy",
    "Satoriz - L'Isle-d'Abeau",
    "Grand Frais - Le Creusot",
    "Grand Frais - Civrieux d'Azergues",
    "Grand Frais - Marsannay-la-Côte",
    "Grand Frais - Essey-lès-Nancy",
    "Grand Frais - Echirolles",
    "Grand Frais - Choisey",
    "Sport 2000 - Chanas",
    "Super U - Vagney",
    "Lidl - Drumettaz-Clarafond",
    "CC La Neuve - Viriat",
    "CC Val Thoiry (01)",
    "Boulanger Macon Sud (71)",
    "Supermarché Match - Villers-lès-Nancy",
    "Frey Soissons - Parc des Moulins",
    "Intermarché - Angers",
    "Aldi - Carpentras",
    "Groupe Bourrelier - Aldi Orgeval  (78)",
    "Groupe Bourrelier - Retail Park Viry Chatillon (91)",
    "E.Leclerc - Le Boulou",
    "Centre commercial Cernay (68)",
    "Marques Avenue Usine Center Gonesse (95)",
    "Marques Avenue - Talange",
    "Marques Avenue Franconville (95)",
    "Marques Avenue Corbeil Essonnes (91)",
    "Marques Avenue Centre Commercial Ile Saint-Denis (93)",
    "KFC EPAGNY (74)",
    "INTERMARCHE SUPER MONTLUCON Pierre Semard (3)",
    "Centre Commercial Bois Bersol - Pessac",
    "Intermarché CORBAIS (MONT-SAINT-GUIBERT)",
    "Action - Libramont",
    "Intermarché Contact SART-DAMES-AVELINES (VILLERS)",
    "Intermarché - Hermalle-sous-Argenteau",
    "Intermarché - Binche",
    "Super U - Luçon",
    "King Jouet Mozac (63)",
    "Frey Clos du Chene Montevrain (77)",
    "Le Plein - Le Mans (Nord) - Auchan",
    "Buffalo Grill - Tarbes",
    "INTERMARCHÉ NANTES",
    "AUCHAN LE PRADET",
    "RETAIL PARK SAINT PIERRE DU MONT",
    "Supermarché Match - Beauvais",
    "GRAND FRAIS SCHWEIGHOUSE SUR MODER",
    "GRAND FRAIS NARBONNE",
    "GRAND FRAIS AVIGNON",
    "ALDI QUETIGNY",
    "ALDI - Rochefort",
    "E.Leclerc - Chécy",
    "SUPER U LA MOTTE SERVOLEX (73)",
    "KFC Narbonne (11)",
    "Intermarché Super MARCHE-EN-FAMENNE",
    "Action - Terville",
    "Intermarché Super FORCHIES-LA-MARCHE",
    "Frey Amiens (80)",
    "Neinver Roppenheim (67)",
    "Popeyes & Buffalo Grill - Limoges",
    "BURGER KING ISTRES (13)",
    "Intermarché super Givry",
    "Intermarché Super HUY",
    "Intermarché Super SPRIMONT",
    "Castin Gilles Villaret - Aldi - Sarcelles (95)",
    "KFC - Sens",
    "Action Noz - Privas",
    "Match Loos (59)",
    "Hôtel Mercure - Hyères",
    "Hôtel Ibis Salon de Provence Sud",
    "Le Plein - Roncq Proximité - Auchan",
    "Patrimonia - Retail Park Plaisir (78)",
    "Au Bureau - Lys lez Lannois",
    "CENTRE E. LECLERC LOUHANS (71)",
    "CENTRE E. LECLERC LUX (71)",
    "Action - Wanze",
    "Ibis - Brussels Erasmus",
    "Intermarché Super BOUSSU",
    "SO - AD delhaize LIERS",
    "AD Delhaize - Rocourt"
];

// Fonction pour géocoder un site
async function geocodeSite(siteName) {
    try {
        const encodedName = encodeURIComponent(siteName + ', France');
        const response = await fetch(`https://nominatim.openstreetmap.org/search?format=json&q=${encodedName}&limit=1`, {
            headers: {
                'User-Agent': 'JCSM-Interventions-App/1.0'
            }
        });
        
        if (response.ok) {
            const data = await response.json();
            if (data && data.length > 0) {
                return {
                    nomSite: siteName,
                    lat: parseFloat(data[0].lat),
                    lng: parseFloat(data[0].lon)
                };
            }
        }
    } catch (error) {
        console.error(`Erreur pour ${siteName}:`, error);
    }
    return null;
}

// Fonction pour géocoder tous les sites (avec pause entre chaque)
async function geocodeAllSites() {
    const results = [];
    const total = sitesList.length;
    
    console.log(`📍 Début du géocodage de ${total} sites...`);
    
    for (let i = 0; i < total; i++) {
        const site = sitesList[i];
        console.log(`[${i + 1}/${total}] Géocodage de: ${site}`);
        
        const result = await geocodeSite(site);
        if (result) {
            results.push(result);
            console.log(`✅ ${site}: ${result.lat}, ${result.lng}`);
        } else {
            console.log(`❌ ${site}: Non trouvé`);
        }
        
        // Pause de 1 seconde entre chaque requête (limite Nominatim)
        if (i < total - 1) {
            await new Promise(resolve => setTimeout(resolve, 1000));
        }
    }
    
    console.log(`\n✅ Géocodage terminé: ${results.length}/${total} sites trouvés`);
    console.log('\n📋 Résultats (à copier dans addSitesCoordinates):');
    console.log(JSON.stringify(results, null, 2));
    
    return results;
}

// Exporter pour utilisation
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { geocodeAllSites, sitesList };
}

