# Redirection HTTP -> HTTPS pour jcsm.cloud
server {
    listen 80;
    server_name jcsm.cloud www.jcsm.cloud;

    return 301 https://jcsm.cloud$request_uri;
}

# Site jcsm.cloud servi en HTTPS
server {
    listen 443 ssl http2;
    server_name jcsm.cloud www.jcsm.cloud;

    root /var/www/jcsm.cloud;
    index index.html index.htm index.php;

    location / {
        try_files $uri $uri/ =404;
    }

    ssl_certificate /etc/letsencrypt/live/jcsm.cloud/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/jcsm.cloud/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}